# This action is meant to be triggered manually via the GitHub UI
name: Cargo publish Check
on:
  push:
    tags:
      - "*" # Run this validation on release tags

jobs:
  release:
    name: Run cargo-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Cache toolchain
        uses: actions/cache@v1
        with:
          path: /usr/share/rust/.cargo
          key: ${{ runner.os }}-rustup
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-release
        run: cargo install cargo-release
      - name: Publish pravega-client-shared (Dry Run)
        run: cargo publish --dry-run -v -p pravega-client-shared
      - name: Publish pravega-client-macros (Dry Run)
        run: cargo publish --dry-run -v -p pravega-client-macros
      - name: Publish pravega-client-channel (Dry Run)
        run: cargo publish --dry-run -v -p pravega-client-channel
      - name: Publish pravega-client-retry (Dry Run)
        run: cargo publish --dry-run -v -p pravega-client-retry
      - name: Publish pravega-connection-pool (Dry Run)
        run: cargo publish --dry-run -v -p pravega-connection-pool
      - name: Publish pravega-client-config (Dry Run)
        run: cargo publish --dry-run -v -p pravega-client-config
      - name: Publish pravega-wire-protocol (Dry Run)
        run: cargo publish --dry-run -v -p pravega-wire-protocol
      - name: Publish pravega-controller-client (Dry Run)
        run: cargo publish --dry-run -v -p pravega-controller-client
      - name: Publish pravega-client-auth (Dry Run)
        run: cargo publish --dry-run -v -p pravega-client-auth
      - name: Publish pravega-client (Dry Run)
        run: cargo publish --dry-run -v -p pravega-client
      - name: Publish pravega-client-shared
        run: cargo publish --token $CARGO_REGISTRY_TOKEN -v -p pravega-client-shared
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish pravega-client-macros
        run: cargo publish --token $CARGO_REGISTRY_TOKEN -v -p pravega-client-macros
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish pravega-client-channel
        run: cargo publish --token $CARGO_REGISTRY_TOKEN -v -p pravega-client-channel
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish pravega-client-retry
        run: cargo publish --token $CARGO_REGISTRY_TOKEN -v -p pravega-client-retry
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish pravega-connection-pool
        run: cargo publish --token $CARGO_REGISTRY_TOKEN -v -p pravega-connection-pool
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish pravega-client-config
        run: cargo publish --token $CARGO_REGISTRY_TOKEN -v -p pravega-client-config
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish pravega-wire-protocol
        run: cargo publish --token $CARGO_REGISTRY_TOKEN -v -p pravega-wire-protocol
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish pravega-controller-client
        run: cargo publish --token $CARGO_REGISTRY_TOKEN -v -p pravega-controller-client
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish pravega-client-auth
        run: cargo publish --token $CARGO_REGISTRY_TOKEN -v -p pravega-client-auth
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish pravega-client
        run: cargo publish --token $CARGO_REGISTRY_TOKEN -v -p pravega-client
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

