# This action is meant to be triggered manually via the GitHub UI
name: Cargo publish Check
on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  release:
    name: Run cargo-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-release
        run: cargo install cargo-release
      - name: Release (Dry Run)
        run: cargo release --workspace # By default cargo-release run in dry-run mode.
 