
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: pythontest

jobs:
  test_tox:
    name: run-tox
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
      - name: Download and Run Pravega standalone
        run: |
          wget https://github.com/pravega/pravega/releases/download/v0.13.0-rc1/pravega-0.13.0.tgz
          tar -xzvf pravega-0.13.0.tgz
          pravega-0.13.0/bin/pravega-standalone > pravega.log 2>&1 &
          sleep 120 && echo "Started standalone"
          tail pravega.log
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install maturin and tox
        run: pip install 'maturin>=0.14,<0.15' virtualenv tox==3.28.0 tox-pyo3
      - name: Test with tox
        run: tox -c python/tox.ini
      - name: Upload Pravega standalone logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: pravega-standalone-log
          path: pravega.log
          retention-days: 5
