
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - enable-tox

name: pythontest

jobs:
  test_tox:
    name: run-tox
    runs-on: ubuntu-18.04
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
      - name: Download and Run Pravega standalone
        run: |
          wget https://github.com/pravega/pravega/releases/download/v0.9.0/pravega-0.9.0.tgz
          tar -xzvf pravega-0.9.0.tgz
          pravega-0.9.0/bin/pravega-standalone > pravega.log 2>&1 &
          sleep 120 && echo "Started standalone"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Install maturin and tox
        run: pip install 'maturin==0.8.3' virtualenv tox
      - name: Test with tox
        run: tox -c bindings/tox.ini
      - name: Upload Pravega standalone logs
        uses: actions/upload-artifact@v2
        with:
          name: pravega-standalone-log
          path: pravega.log
          retention-days: 5
